version: '3.3'

services:

  backend:
    container_name: word_cloud_backend
    hostname: word_cloud_backend
    build: ./Backend
    image: ghcr.io/trisnol/word-cloud-backend

    ports:
      - 3000:3000
    restart: unless-stopped

  frontend:
    container_name: word_cloud_frontend
    hostname: word_cloud_frontend
    build: ./Frontend
    image: ghcr.io/trisnol/word-cloud-frontend

    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - backend
